language: node_js
node_js:
  - "5.1"
env:
  - CXX=g++-4.8
before_script:
  - "npm run lint"
after_success:
  - "npm run cover"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
