language: node_js
node_js:
  - "5.3"
before_script:
  - "rm rf node_modules"
  - "npm install"
  - "npm run lint"
after_success:
  - "npm run cover"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
