version: 2
    
jobs:
  build:
    working_directory: /react-day-picker
    docker:
      - image: node:7.9.0
        environment:
          TEST_REPORT_PATH: "reports"
  
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn --pure-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "/usr/local/share/.cache/yarn"
            - "./node_modules"
      - run: mkdir -p reports
      - run: yarn lint -- --format junit --output-file reports/eslint.xml
      - run: yarn dtslint
      - run: yarn test -- --coverage --testResultsProcessor jest-junit-reporter
      - run: yarn codecov
      - store_test_results:
          path: reports/
      - run: 
          name: Build lib
          command: yarn run build
  docs_publish:
    working_directory: /react-day-picker
    docker:
      - image: node:7.9.0
    steps: 
      - run: yarn docs:publish
      
workflows: 
  version: 2
  build_and_test:
    jobs:
      - docs_publish:
          filters:
              branches:
                only: master
