defaults: &defaults
  working_directory: /root/react-day-picker
  docker:
    - image: node:8.9
      environment:
        TEST_REPORT_PATH: "reports"

version: 2

jobs:
  checkout-and-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/react-day-picker/node_modules
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint sources
          command: yarn lint --format junit --output-file reports/eslint.xml
      - run:
          name: Lint TypeScript definition files
          command: yarn dtslint
      - run:
          name: Run unit tests
          command: yarn test --ci --coverage --colors --testResultsProcessor jest-junit-reporter
      - run:
          name: Uploade code-coverage results
          command: yarn codecov
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/react-day-picker/node_modules
      - store_test_results:
          path: ~/react-day-picker/reports
      - persist_to_workspace:
          root: .
          paths:
            - "*"
            - src

  build-project:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/react-day-picker
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/react-day-picker/node_modules
      - run: yarn
      - run: yarn build

  build-docs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-docs-v1-{{ checksum "package.json" }}
      - run: cd docs && yarn install
      - save_cache:
          key: cache-docs-v1-{{ checksum "package.json" }}
          paths:
            - "./docs/node_modules"
      - run: |
          git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
          git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - run: cd docs && yarn build
      - run: cd docs && yarn docs-publish

workflows:
  version: 2
  build:
    jobs:
      - checkout-and-test
      - build-project:
          requires:
            - checkout-and-test
          filters:
            branches:
              only: master
      - build-docs:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
