blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/gpbl/react-day-picker/discussions
    about: Please ask and answer questions here. It's a good place for discussing new features too! Thanks for keeping the issues list clean.
