blank_issues_enabled: false
contact_links:
  - name: Get Help and Technical Support
    url: https://github.com/gpbl/react-day-picker/discussions
    about: Please ask and answer questions **here**. Thanks for keeping the issues list clean!
  - name: Propose a New Feature
    url: https://github.com/gpbl/react-day-picker/discussions
    about: Share your idea and help add it to the next version.
