blank_issues_enabled: false
contact_links:
  - name: Get Help and Technical Support
    url: https://github.com/gpbl/react-day-picker/discussions
    about: Please ask and answer questions **here**. Thanks for keeping the issues list clean!
  - name: Propose New Features
    url: https://github.com/gpbl/react-day-picker/discussions
    about: Share your ideas and wishes for the next DayPicker version.
