name: Node CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install Dependencies
        working-directory: ./package
        run: yarn install
      - name: Lint files
        working-directory: ./package
        run: yarn coverage

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install Dependencies
        working-directory: ./package
        run: yarn install
      - name: Run Unit Tests
        working-directory: ./package
        run: yarn test

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./package
        run: yarn install
      - name: Build
        working-directory: ./package
        run: yarn build
