name: Node CI

on:
  pull_request:
    branches:
    - next
  push:
    branches:
      - next
        
jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Logs
      uses: bdougie/loglify@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Lint soruce
      run: |
        yarn lint
        yarn lint-types
    - name: Build
      run: yarn build

      env:
        CI: true
