name: Node CI

on:
  pull_request:
    branches:
    - next
  push:
    branches:
      - next
        
jobs:
  logs4netlify:
    name: Logs for Netlify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Logs
      uses: bdougie/loglify@master:
     
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
        yarn test 
      env:
        CI: true
